apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: uec-dos-api-dev
  name: uec-dos-api-cs
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1 # how many pods we can add at a time
      maxUnavailable: 0 # maxUnavailable define how many pods can be unavailable during the rolling update
  template:
    metadata:
      labels:
        app: uec-dos-api-cs
    spec:
      containers:
        - name: uec-dos-api-cs
          image: 461183108257.dkr.ecr.eu-west-2.amazonaws.com/uec/dos-api/capacity-status/api:0.0.1
          envFrom:
            - configMapRef:
                name: uec-dos-api-cs-configmap
          ports:
            - containerPort: 8443
              protocol: TCP
          resources:
            requests:
              memory: "0Mi"
              cpu: "0m"
            limits:
              memory: "2048Mi"
              cpu: "1000m"
          imagePullPolicy: Always
