kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: uec-dos-api-cs-allow-external-ingress
spec:
  podSelector:
    matchLabels:
      app: uec-dos-api-cs
  ingress:
    - from: []
      ports:
        - protocol: TCP
          port: 8443
        #  - protocol: TCP
        #    port: 8060
        #- protocol: TCP
        # port: 443
