bases:
  - ../../base

patchesStrategicMerge:
  - uec-dos-api-cs-proxy-ingress-customisation.yaml

namespace: K8S_APP_NAMESPACE_TO_REPLACE

configMapGenerator:
  - name: uec-dos-api-cs-configmap
    behavior: merge
    literals:
      - API_DB_HOST=API_DB_HOST_TO_REPLACE
      - DOS_DB_HOST=DOS_DB_HOST_TO_REPLACE
      - DJANGO_SECRET_KEY=DJANGO_SECRET_KEY_TO_REPLACE
      - DJANGO_DEBUG=DJANGO_DEBUG_TO_REPLACE
      - RESET_STATUS_IN_DEFAULT_VALUE=SERVICE_RESET_STATUS_IN_DEFAULT_VALUE_TO_REPLACE
      - RESET_STATUS_IN_MIN_VALUE=SERVICE_RESET_STATUS_IN_MIN_VALUE_TO_REPLACE
      - RESET_STATUS_IN_MAX_VALUE=SERVICE_RESET_STATUS_IN_MAX_VALUE_TO_REPLACE

commonLabels:
  env: dev
